# Generated by Django 3.2.19 on 2023-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='user_id',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
