# Generated by Django 3.2.19 on 2023-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0002_star_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='epoch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='star',
            name='period',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='star',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
