# Generated by Django 3.2.19 on 2023-06-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAstro', '0003_auto_20230627_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='user_id',
        ),
    ]
