# Generated by Django 3.2.16 on 2023-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('route_len', models.CharField(max_length=10)),
                ('points', models.CharField(max_length=1000)),
            ],
        ),
    ]
