# Generated by Django 4.1.5 on 2023-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='routeId',
        ),
        migrations.AddField(
            model_name='place',
            name='point2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
