# Generated by Django 4.1.5 on 2023-02-13 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_remove_place_routeid_place_point2'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='point1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
