# Generated by Django 4.1.5 on 2023-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_place_point1_route_name_route_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='userId',
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.CharField(default='', max_length=255),
        ),
    ]
