# Generated by Django 4.1.5 on 2023-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_route_distancem_route_timem'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='isStatic',
            field=models.BooleanField(default=False),
        ),
    ]
