# Generated by Django 4.1.5 on 2023-02-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_route_isstatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='isStatic',
        ),
    ]
