# Generated by Django 4.1.5 on 2023-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_route_isstatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='places',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
