# Generated by Django 4.1.5 on 2023-02-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_alter_route_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='point2',
            field=models.CharField(default='', max_length=4095),
        ),
        migrations.AlterField(
            model_name='route',
            name='places',
            field=models.CharField(default='', max_length=4095),
        ),
    ]
